import express from "express";
import auth from "../middleware/auth.js";
import { list, create, update, remove } from "../controllers/clientController.js";
const router = express.Router();
router.use(auth);
router.get("/", list);
router.post("/", create);
router.put("/:id", update);
router.delete("/:id", remove);
export default router;
